# Generated by Django 5.0.6 on 2024-05-10 13:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('type', models.TextField()),
                ('uniqueName', models.UUIDField(default=uuid.UUID('5495d6fc-3fdf-43c0-ac34-976eaeb1a28f'))),
                ('price', models.IntegerField()),
                ('uploadDate', models.DateTimeField(default='django.utils.timezone.now')),
            ],
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('uniqueName', models.UUIDField(default=uuid.UUID('3bc7017d-5266-4e65-8f47-134ebb37c3ca'))),
                ('asset', models.FileField(upload_to='')),
            ],
        ),
    ]
