# Generated by Django 5.0.6 on 2024-05-10 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uniqueName',
            field=models.UUIDField(default=uuid.UUID('0dcc9ef9-521d-41f0-8874-15ec937db35b')),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='uniqueName',
            field=models.UUIDField(default=uuid.UUID('e21e8505-63c8-4831-bc4a-55e2dc72c3bb')),
        ),
    ]
